# Generated by Django 4.0.5 on 2022-07-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Digite seu nome')),
                ('email', models.EmailField(max_length=200, verbose_name='Digite seu email')),
                ('password', models.CharField(max_length=200, verbose_name='Digite a senha')),
                ('idade', models.IntegerField(verbose_name='Digite sua idade')),
                ('altura', models.IntegerField(verbose_name='Digite sua altura')),
                ('peso', models.IntegerField(verbose_name='Digite seu peso')),
            ],
        ),
    ]
