# Generated by Django 4.0.5 on 2022-07-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Digite sua altura'),
        ),
    ]
