# Generated by Django 4.0.5 on 2022-08-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamentos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
