# Generated by Django 4.0.5 on 2022-08-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_alter_equipamentos_descr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamentos',
            old_name='imgagem',
            new_name='imagem',
        ),
        migrations.AlterField(
            model_name='equipamentos',
            name='status',
            field=models.CharField(choices=[('Funcionando', 'Funcionando'), ('Manutenção', 'Manutenção'), ('Quebrado', 'Quebrado')], max_length=11),
        ),
    ]
