# Generated by Django 4.0.5 on 2022-08-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_rename_imgagem_equipamentos_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamentos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
